/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banking_application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author rebeka
 */
public class User_Search_Update_user extends javax.swing.JFrame {

    Connection con;
    PreparedStatement pstm;
    ResultSet rs;
    
    public User_Search_Update_user() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RGGender = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TFUserName = new javax.swing.JTextField();
        TFName = new javax.swing.JTextField();
        RBMale = new javax.swing.JRadioButton();
        RBFemale = new javax.swing.JRadioButton();
        TFPhone = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAAddress = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        BTSearch = new javax.swing.JButton();
        BTUpdate = new javax.swing.JButton();
        BTReset = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TXID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User Update Form");
        setPreferredSize(new java.awt.Dimension(650, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Update User ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" User Name :  ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Name : ");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" Gender : ");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" Date of Birth : ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(" Phone : ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" Address : ");

        RGGender.add(RBMale);
        RBMale.setForeground(new java.awt.Color(255, 255, 255));
        RBMale.setText("Male");

        RGGender.add(RBFemale);
        RBFemale.setForeground(new java.awt.Color(255, 255, 255));
        RBFemale.setText("Female");

        TAAddress.setColumns(20);
        TAAddress.setRows(5);
        jScrollPane1.setViewportView(TAAddress);

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));

        BTSearch.setText("Search");
        BTSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSearchActionPerformed(evt);
            }
        });

        BTUpdate.setText(" Update ");
        BTUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTUpdateActionPerformed(evt);
            }
        });

        BTReset.setText("Reset");
        BTReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(BTReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTSearch)
                .addGap(109, 109, 109)
                .addComponent(BTUpdate)
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTSearch)
                    .addComponent(BTUpdate)
                    .addComponent(BTReset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(203, 203, 203))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(TFUserName)
                    .addComponent(TFName)
                    .addComponent(TFPhone)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RBMale)
                        .addGap(18, 18, 18)
                        .addComponent(RBFemale)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(TXID))
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(TXID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RBMale)
                    .addComponent(RBFemale))
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TFPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 490));

        setSize(new java.awt.Dimension(543, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSearchActionPerformed
       
        
        // for search
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root","123");
            
            //user_information's column name ID, Name, UserName, Password, Gender, DOB, Phone, Address, UserType
            
            String query = "select  UserName,Name, Password, Gender, DOB, Phone, Address, UserType  from user_information  where UserName=? ";
            pstm = con.prepareStatement(query);
            pstm.setString(1, TFUserName.getText().toString());
            //pstm.setString(2, TFName.getText().toString());
            
            rs=pstm.executeQuery();
            
            if(rs.next()){
//                String i= rs.getString("Acc");
//                TFName.setText(i);
                String Name= rs.getString("Name");
                TFName.setText(Name);
                
                java.sql.Date birthdate = rs.getDate("DOB");
                DCDOB.setDate(birthdate);
                
                
                String phone= rs.getString("Phone");
                TFPhone.setText(phone);
                
                String address= rs.getString("Address");
                TAAddress.setText(address);
               
//district and gender ase ni cz of i don't declare that      
                



String gender= rs.getString("Gender");
                //RGGender.setSelected(gender);
                 if(gender.equalsIgnoreCase("male")){
                     RBMale.setSelected(true);
                 }else{
                     RBFemale.setSelected(true);
                 }
            }
        
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BTSearchActionPerformed

    private void BTUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTUpdateActionPerformed
        try {
            //update the user information in database
            getAllRecord();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BTUpdateActionPerformed

    private void BTResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTResetActionPerformed
        // for reset
        TFUserName.setText("");
        TFName.setText("");
        RGGender.clearSelection();
           
              
        DCDOB.setDate(null);
        TFPhone.setText("");
        TAAddress.setText("");
        
        
    }//GEN-LAST:event_BTResetActionPerformed

    public void getAllRecord() throws SQLException{
        String UserName,Name,Gender,DOB,Phone,Address,id;
        
        id=TXID.getText();
        UserName=TFUserName.getText();
        Name=TFName.getText();
        //Gender
            if(RBMale.isSelected()){
               Gender="Male"; 
            }else{
                Gender="Female"; 
            }
        DOB=((JTextField)DCDOB.getDateEditor().getUiComponent()).getText();
        Phone=TFPhone.getText();
        Address =TAAddress.getText();
        
        
        Connection con=null;
        Statement stmt=null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test", "root", "123");
        stmt=con.createStatement();
        
        int count=0;
        count=stmt.executeUpdate("update user_information set  Name='"+Name +"', UserName='"+UserName +"', Gender='"+Gender +"', DOB='"+DOB +"', Phone='"+ Phone+"', Address='"+Address +"' where ID='"+id+"'  ");
        if(count>0){
            JOptionPane.showMessageDialog(rootPane, " Updated information of user");
        }else{
            JOptionPane.showMessageDialog(rootPane, " Failed information of user");
        }
        }catch(Exception e){
            e.printStackTrace();
        }finally{
            con.close();
            stmt.close();
        }
    
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Search_Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Search_Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Search_Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Search_Update_user.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Search_Update_user().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTReset;
    private javax.swing.JButton BTSearch;
    private javax.swing.JButton BTUpdate;
    private javax.swing.JRadioButton RBFemale;
    private javax.swing.JRadioButton RBMale;
    private javax.swing.ButtonGroup RGGender;
    private javax.swing.JTextArea TAAddress;
    private javax.swing.JTextField TFName;
    private javax.swing.JTextField TFPhone;
    private javax.swing.JTextField TFUserName;
    private javax.swing.JTextField TXID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
